In [2]:
import dash
import dash_html_components as html
import dash_core_components as dcc
import plotly.graph_objs as go
import plotly.express as px
import dash_table
import seaborn as sns
import pandas as pd 
import numpy as np


df = pd.read_csv('Data_ ReliefWeb Crisis Figures Data - latest_figures.csv')
df.head(1)

,crisis_index,crisis_name,crisis_iso3,figure_name,figure_source,figure_value,figure_date,figure_url
0,0,Afghanistan,AFG,People in Need,OCHA,9400000,2019-12-31,https://m.reliefweb.int/report/3460128

In [3]:
numbers = df[['crisis_name','figure_name','figure_value']]
numbers

,crisis_name,figure_name,figure_value
0,Afghanistan,People in Need,9400000
1,Afghanistan,People Targeted for Assistance,7100000
2,Afghanistan,Children in Need,5100000
3,Afghanistan,People in Food Crisis/Emergency (IPC phase 3+),10232000
4,Afghanistan,Undocumented Afghan Returnees from Iran (per y...,45113
...,...,...,...
587,Zimbabwe,Refugees & Asylum-Seekers in Zimbabwe,20129
588,Zimbabwe,DRC Refugees in Zimbabwe,10889
589,Zimbabwe,Mozambican Asylum-Seekers in Zimbabwe,8048
590,Zimbabwe,People Received WFP Food Assistance (per month),2640000
591,Zimbabwe,New IDPs by Natural Disasters (per year),52000

In [4]:
# data = df.groupby(['People in Need', 'People Targeted for Assistance']) 
# data

total= df['figure_value'].groupby(df['crisis_name']) 
total.first()

crisis_name
Afghanistan                          9400000
Bangladesh                           1300000
Burkina Faso                         2200000
Burundi                              1700000
Cameroon                             4400000
Central African Republic             2600000
Chad                                 5300000
Colombia                             5177711
Democratic Republic of the Congo    15600000
Ethiopia                             8400000
Haiti                                4600000
Iraq                                 4100000
Kenya                                2390000
Lebanon                              3200000
Libya                                 900000
Mali                                 3600000
Mozambique                           2500000
Myanmar                               986000
Niger                                3200000
Nigeria                              7700000
Somalia                              5200000
South Sudan                          7500000
Sudan                                9300000
Syria                               11100000
Ukraine                              3400000
Venezuela                            7000000
Yemen                               24000000
Zimbabwe                             5100000
occupied Palestinian territory       2400000
Name: figure_value, dtype: int64

In [5]:
options = ['People in Need', 'People Targeted for Assistance'] 
  
# selecting rows based on condition 
r = numbers.loc[numbers['figure_name'].isin(options)]

print(r)

                          crisis_name                     figure_name  \
0                         Afghanistan                  People in Need
1                         Afghanistan  People Targeted for Assistance
40                       Burkina Faso                  People in Need
41                       Burkina Faso  People Targeted for Assistance
57                            Burundi                  People in Need
58                            Burundi  People Targeted for Assistance
65                           Cameroon                  People in Need
66                           Cameroon  People Targeted for Assistance
89           Central African Republic                  People in Need
90           Central African Republic  People Targeted for Assistance
115                              Chad                  People in Need
116                              Chad  People Targeted for Assistance
134                          Colombia                  People in Need
135                          Colombia  People Targeted for Assistance
143  Democratic Republic of the Congo                  People in Need
144  Democratic Republic of the Congo  People Targeted for Assistance
192                          Ethiopia                  People in Need
193                          Ethiopia  People Targeted for Assistance
219                             Haiti                  People in Need
220                             Haiti  People Targeted for Assistance
229                              Iraq                  People in Need
230                              Iraq  People Targeted for Assistance
271                           Lebanon                  People in Need
272                           Lebanon  People Targeted for Assistance
279                             Libya                  People in Need
280                             Libya  People Targeted for Assistance
290                              Mali                  People in Need
291                              Mali  People Targeted for Assistance
313                        Mozambique                  People in Need
314                        Mozambique  People Targeted for Assistance
321                           Myanmar                  People in Need
322                           Myanmar  People Targeted for Assistance
332                             Niger                  People in Need
333                             Niger  People Targeted for Assistance
345                           Nigeria                  People in Need
346                           Nigeria  People Targeted for Assistance
379    occupied Palestinian territory                  People in Need
380    occupied Palestinian territory  People Targeted for Assistance
396                           Somalia                  People in Need
397                           Somalia  People Targeted for Assistance
439                       South Sudan                  People in Need
440                       South Sudan  People Targeted for Assistance
482                             Sudan                  People in Need
483                             Sudan  People Targeted for Assistance
501                             Syria                  People in Need
502                             Syria  People Targeted for Assistance
535                           Ukraine                  People in Need
536                           Ukraine  People Targeted for Assistance
547                         Venezuela                  People in Need
548                         Venezuela  People Targeted for Assistance
559                             Yemen                  People in Need
560                             Yemen  People Targeted for Assistance

     figure_value
0         9400000
1         7100000
40        2200000
41        1800000
57        1700000
58         630000
65        4400000
66        2600000
89        2600000
90        1600000
115       5300000
116       3000000
134       5177711
135       1300000
143      15600000
144       8100000
192       8400000
193       7000000
219       4600000
220       2100000
229       4100000
230       1770000
271       3200000
272       2800000
279        900000
280        300000
290       3600000
291       2900000
313       2500000
314       2000000
321        986000
322        848000
332       3200000
333       1900000
345       7700000
346       5700000
379       2400000
380       1500000
396       5200000
397       3000000
439       7500000
440       5600000
482       9300000
483       6100000
501      11100000
502       9000000
535       3400000
536       2000000
547       7000000
548       3500000
559      24000000
560      15600000

In [6]:
app = dash.Dash()

app.layout = dash_table.DataTable(
    id='table',
    columns=[{"crisis_name": i, "id": i} for i in df.columns],
    data=r.to_dict('records'),
)

In [7]:
def generate_table(dataframe, max_rows=26):
    return html.Table(
        # Header
        [html.Tr([html.Th(col) for col in r.columns]) ] +
        # Body
        [html.Tr([
            html.Td(r.iloc[i][col]) for col in r.columns
        ]) for i in range(min(len(r), max_rows))]
    )

In [11]:
app.layout = html.Div([
                   
                    dcc.Graph(id='stacked bargraph',
                        figure = px.bar(r, x="figure_name", y="figure_value", 
                            height=10000, 
                            title='Numbers according to data')),    

                    dcc.Graph(id='grouped bargraph', 
                        figure = px.bar(df, x="crisis_name", y="figure_value", color='figure_name', 
                            barmode ='group', height=650, 
                            title='crisis_ios3')),   

                    dcc.Interval(id='interval-component', 
                        interval=2000,
                        n_intervals=0)




                    ])

In [12]:
if __name__ == '__main__':
    app.run_server(debug=True)

Running on http://127.0.0.1:8050/
Debugger PIN: 993-715-900
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on

SystemExit: 1

/home/recruit/Desktop/Umuzi/dashboard/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3339: UserWarning:

To exit: use 'exit', 'quit', or Ctrl-D.